
services:
  app:
    image: openjdk:17-jdk-slim
    container_name: library-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./data:/data
      - ./target:/app/target
    command: ["java", "-jar", "/app/target/Library-0.0.1-SNAPSHOT.jar"]  # Actualiza el nombre del JAR
